### ISSUE TITLE
Feedback!

### ISSUE THREAD

**Issue by gypsydave5** [AndreiZernov/learn_go_with_saltpay_exercise_one#1]
👋 hey Andrei - here we go!

### Error handling

this

https://github.com/AndreiZernov/Learn-Go-with-Saltpay---Exercise-1/blob/d6d1847d8321f93abb7c8d5d7a1ebc5d3f3bde32/adapters/error_handler/handle_panic.go#L3-L7

is not really how we deal with errors in Go. Panics should, ideally, never happen. They're not like exceptions in every other language. They're more for when things go _very_ wrong - segmentation faults, out of memory, oh noes! When developing a piece of code, you might have a through `panic`s spread around as placeholders, but generally speaking: never, ever, panic.

Instead of using exceptions, Go has errors as just another return value from its functions. The expectation is that you either deal with the error straight afterwards, or forward it on to the caller.

So we get the idiomatic Go:

```go
err := DoSomething()
if err != nil {
  logger.log(fmt.Sprintf("Couldn't DoSomething: %s", err))
  return err
}
return nil
```

Every time a function can return an error, check if its nil, and then take action.

So, to be concrete regarding your code,

https://github.com/AndreiZernov/Learn-Go-with-Saltpay---Exercise-1/blob/059b65b5c86a18fbec2e25be66d364c349c027df/adapters/temphttp/fibo_client.go#L18

should really be *either* returning an `error` when things go wrong with the subroutine calls, or handing the error each time - probably with something like a `Logger.Fatal()` in this case as "handling" here means "exiting the program and dying gracefully".

`panic` is never a graceful way to die. So take the opportunity to log something nicer out too!

Take a read of: https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/pointers-and-errors which (hopefully) explains more, and the ever-wonderful https://gobyexample.com/errors.

### Acceptance level testing

Just wanted to say, big fan, good work! But you should have similar tests for `fibo` and `math` as you do for `add` and `uuid`.

This is obviously an exciting challenge! But there's no reason we can't do something similar: start the binary (a server) and start hitting it with requests...

### Declare things at the top

https://github.com/AndreiZernov/Learn-Go-with-Saltpay---Exercise-1/blob/4a3fd04b119e6b7ad036a327b27209ced8134ad7/cmd/add/main_test.go#L72-L74

Just while we're looking at the acceptance tests, this sort of block should really be at the top of the file or function it's in - kinda like you'd do in C. It's introducing the major players in our drama below. And this one can also be a `const`. See again https://gobyexample.com/constants.

**Comment by gypsydave5** [comment]
### Calculating Fibonacci

There is a way of calculating the nth term of the Fibonacci series _without_ calculating the previous two terms. It's called [Binet's Formula](https://en.wikipedia.org/wiki/Fibonacci_number#Binet's_formula) and might help speed up the algorithm for smaller numbers. Something to experiment with (and use `math.Phi` 😄 ).

**Comment by gypsydave5** [comment]
## Add

https://github.com/AndreiZernov/Learn-Go-with-Saltpay---Exercise-1/blob/059b65b5c86a18fbec2e25be66d364c349c027df/domain/calculator/add.go#L24-L45

This pleases me not.

Our `add` function is extremely coupled to a particular type of formatted string. So much so that the callers of this function are having to parse everything out of a particular format, then parse it back into a comma separated list, and then clean it up so it's the "right" sort of comma separted list, as in the `GetData` function and the add handler

https://github.com/AndreiZernov/Learn-Go-with-Saltpay---Exercise-1/blob/240f3c00ceaef9a738b11f1eaa3fc3d23367bcf8/adapters/temphttp/handlers/add_request_handler.go#L50-L51

a string is not a good representation for a collection of numbers in Go. A good representation for a collection of numbers would be a `[]int`.

Passing around a string means that your code has to concern itself _again_ with converting from a string to an int inside the `add` function:

https://github.com/AndreiZernov/Learn-Go-with-Saltpay---Exercise-1/blob/059b65b5c86a18fbec2e25be66d364c349c027df/domain/calculator/add.go#L29

--- 

final point: the `err` is never getting handled! If there was an error in `AtoI` you will never see it.

**Comment by AndreiZernov** [comment]
> ### Declare things at the top
> https://github.com/AndreiZernov/Learn-Go-with-Saltpay---Exercise-1/blob/4a3fd04b119e6b7ad036a327b27209ced8134ad7/cmd/add/main_test.go#L72-L74
> 
> Just while we're looking at the acceptance tests, this sort of block should really be at the top of the file or function it's in - kinda like you'd do in C. It's introducing the major players in our drama below. And this one can also be a `const`. See again https://gobyexample.com/constants.

Thank you so much for your feedback =) Time to make some adjustments =) 
**Constants** - adjusted all variables to constants where it is applicable.

**Comment by AndreiZernov** [comment]
> ### Error handling
> this
> 
> https://github.com/AndreiZernov/Learn-Go-with-Saltpay---Exercise-1/blob/d6d1847d8321f93abb7c8d5d7a1ebc5d3f3bde32/adapters/error_handler/handle_panic.go#L3-L7
> 
> is not really how we deal with errors in Go. Panics should, ideally, never happen. They're not like exceptions in every other language. They're more for when things go _very_ wrong - segmentation faults, out of memory, oh noes! When developing a piece of code, you might have a through `panic`s spread around as placeholders, but generally speaking: never, ever, panic.
> 
> Instead of using exceptions, Go has errors as just another return value from its functions. The expectation is that you either deal with the error straight afterwards, or forward it on to the caller.
> 
> So we get the idiomatic Go:
> 
> ```go
> err := DoSomething()
> if err != nil {
>   logger.log(fmt.Sprintf("Couldn't DoSomething: %s", err))
>   return err
> }
> return nil
> ```
> 
> Every time a function can return an error, check if its nil, and then take action.
> 
> So, to be concrete regarding your code,
> 
> https://github.com/AndreiZernov/Learn-Go-with-Saltpay---Exercise-1/blob/059b65b5c86a18fbec2e25be66d364c349c027df/adapters/temphttp/fibo_client.go#L18
> 
> should really be _either_ returning an `error` when things go wrong with the subroutine calls, or handing the error each time - probably with something like a `Logger.Fatal()` in this case as "handling" here means "exiting the program and dying gracefully".
> 
> `panic` is never a graceful way to die. So take the opportunity to log something nicer out too!
> 
> Take a read of: https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/pointers-and-errors which (hopefully) explains more, and the ever-wonderful https://gobyexample.com/errors.

**Error handling**  
Yes, it is a big mistake. I was relaying on the panic as it did help me to through the _screaming_ error if something wrong happened. 
Thank you so much for the links. Digging deeper, I found one more article which gives a very detailed explanation about different error handling techniques  [Don’t just check errors, handle them gracefully ](https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully)
I decided to try **Annotating errors** with [github.com/pkg/errors](https://godoc.org/github.com/pkg/errors) package.
I did also some adjustments for testing. Is it right to create the _error testing_ to reuse the same functions?

**Comment by gypsydave5** [comment]
Good - the `panic`s have gone!

But...

https://github.com/AndreiZernov/Learn-Go-with-Saltpay---Exercise-1/blob/5b33157fa8272d88f75b50e7e3cff04298afaef4/adapters/files/write_file.go#L10-L21

this is no longer "handling" the error - it's logging it. But how will the calling function know that something has gone wrong? Or how can we recover?

Also, on the subject of this bit of code

## defer `file.Close()`

```go
func WriteFile(path, data string) {
	file, openErr := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
        // do stuff
	closeErr := file.Close()
	error_handler.AnnotatingError(closeErr, "Failed to close file")
}
```

is usually written as 

```go
func WriteFile(path, data string) {
	file, openErr := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
        defer file.Close()
        // do stuff
}
```

**Comment by AndreiZernov** [comment]
> ### Acceptance level testing
> Just wanted to say, big fan, good work! But you should have similar tests for `fibo` and `math` as you do for `add` and `uuid`.
> 
> This is obviously an exciting challenge! But there's no reason we can't do something similar: start the binary (a server) and start hitting it with requests...

I might managed to do one Acceptance test for math, but I am not sure if it is correct. I can test it all before the server starts, but then I struggle to find how to trigger calls to this server to test it properly. Could you please give me advice how it would be possible to test, maybe you have an example =) 
I have the same problem with my fibo Acceptance test.

**Comment by AndreiZernov** [comment]
> ### Calculating Fibonacci
> There is a way of calculating the nth term of the Fibonacci series _without_ calculating the previous two terms. It's called [Binet's Formula](https://en.wikipedia.org/wiki/Fibonacci_number#Binet's_formula) and might help speed up the algorithm for smaller numbers. Something to experiment with (and use `math.Phi` 😄 ).

I have updated the Fibonacci number calculation based on Binet's Formula. But now I have some miscalculations for big numbers, such as the number at position 94 should be  `7540113804746346429` but I got `7540113804746344448`. Probably it is related to using floats during the calculation. Could you please advise me on this topic? =)

**Comment by AndreiZernov** [comment]
> this is no longer "handling" the error - it's logging it. But how will the calling function know that something has gone wrong? Or how can we recover?
> 
> Also, on the subject of this bit of code

I am not sure about recovering, would you might give another example. =) Sorry, I might was trying to use the same approach for all but now found myself lost. 
I tried to reconfigure the error handling and now passing the errors with annotation to higher function (mostly main, and then handle it).

**Comment by AndreiZernov** [comment]
> Our `add` function is extremely coupled to a particular type of formatted string. So much so that the callers of this function are having to parse everything out of a particular format, then parse it back into a comma separated list, and then clean it up so it's the "right" sort of comma separted list, as in the `GetData` function and the add handler

I completely agree, I have updated the data flow completely. No more strings =) Looks much better, it allowed me to delete so much unnecessary lines. Thank you so much for the suggestion.

**Comment by AndreiZernov** [comment]
@gypsydave5 Could you please recommend me what would be the best way to generate one billion uuids. I tested many different approaches, but the best I can get is 25 minutes =( 
And another part is to find the correct key through these one billion records. What would you recommend me to do to search of this key in 1 billion of unsorted keys =) 
Thank you so much for you time =)
